### PR TITLE
Create pylint.yml to enable automated linting

### PR DESCRIPTION
**Pull request by barndawgie**

### CODE REVIEW

**Comment by barndawgie** [comment]
LGTM

**Comment by barndawgie** [comment]
Mistake.

**Comment by tronikos** [comment]
IMO, it would be better to spend time incorporating the official esphome github workflows https://github.com/esphome/esphome/tree/dev/.github/workflows than trying to roll out our own.
In general flake8 is superior to pylint and flake8 is already included in the pre-commit even though I haven't enabled it yet. For now you have to manually run it. I'm hesitant enabling it because it might block people contributing if they don't have pre-commit installed.

**Comment by barndawgie** [comment]
I was just playing around and accidentally sent this PR here instead of my forked main.

I would fall in the bucket of people who might get blocked but if we can point people to straightforward instructions that might be enough?

**Pull request closed without merging**
